package engine.tools;

/**
 * A list of several compound names.
 * @author Matthew Page
 * @version 2.0
 */

public enum CompoundName {
	
	aceticAcid("acetic acid", "5% solution white vinegar", 60.06),
	acetone("acetone", "acetone", 50.08),
	acetyleneGas("acetylene gas", "ethyne", 26.04),
	acetylsalicylicAcid("acetylsalicylic acid", "aspirin", 180.157),
	aluminium("aluminium", "aluminium", 26.981539),
	aluminiumHydroxide("aluminium hydroxide", "alumina hydrate", 78),
	aluminiumOxide("aluminium oxide", "alumina", 101.96),
	aluminiumAmmoniumSulfate("aluminium ammonium sulfate", "ammonium alum", 237.15),
	aluminiumPotassiumSulfate("aluminium potassium sulfate", "alum potassium aluminium sulphate", 258.205),
	aluminiumSulfate("aluminium sulfate", "flocculating powder", 342.15),
	ammonia("ammonia", "ammonium hydroxide", 17.031),
	ammoniumBicarbonate("ammonium bicarbonate", "salt of hartshorn", 79.056),
	ammoniumBifluoride("ammonium bifluoride", "ammonium hydrogen fluoride", 57.04), 
	ammoniumBromide("ammonium bromide", "ammonium bromide", 97.94),
	ammoniumCarbonate("ammonium carbonate", "smelling salts", 96.09),
	ammoniumChloride("ammonium chloride", "soldering flux", 53.49),
	ammoniumNitrate("ammonium nitrate", "ammonium nitrate", 80.053),
	ammoniumPersulfate("ammonium persulfate", "ammonium peroxodisulphate", 228.18),
	ammoniumPhosphate("ammonium phosphate", "fertilizer", 149.09),
	ammoniumSulfate("ammonium sulfate", "ammonium sulfate", 132.14),
	argonGas("argon gas", "argon", 39.948),
	ascorbicAcid("ascorbic acid", "vitamin c", 167.12),
	bariumCarbonate("barium carbonate", "barium carbonate", 197.34),
	bariumSulfate("barium sulfate", "lithopone", 233.43),
	benzoylPeroxide("benzoyl peroxide", "benzoic acid peroxide", 242.23),
	bismuth("bismuth", "lead free shot", 208.9804),
	bismuthSubsalicylate("bismuth subsalicylate", "pepto bismol", 362.093),
	boricAcid("boric acid", "ant killer", 61.83),
	bromthymolBlue("bromthymol blue", "ph test", 624.38),
	butane("butane", "butane", 58.12),
	caffein("caffeine", "no doz", 194.19),
	cadmiumSulfide("cadmium sulfide", "cadmium yellow", 144.48),
	calciumCarbide("calcium carbide", "calcium carbide", 64.099),
	calciumCarbonate("calcium carbonate" ,"limestone", 100.0869),
	calciumChloride("calcium chloride", "laundry aid", 110.98),
	calciumHydroxide("calcium hydroxide", "slaked lime", 74.093),
	calciumHypochlorite("calcium hypochlorite", "calcium hypochlorite", 142.98),
	calciumNitrate("calcium nitrate", "norwegian saltpeter", 164.088),
	calciumOxide("calcium oxide", "lime", 56.0774),
	calciumPhosphate("calcium phosphate", "superphosphate", 502.31),
	calciumSulfate("calcium sulfate", "calcium sulfate", 136.14),
	camphor("camphor", "camphor", 152.23),
	carbon("carbon", "soot", 12.011),
	carbonDioxide("carbon dioxide", "carbon dioxide", 44.01),
	carbonicAcid("carbonic acid", "carbonic acid", 62.03),
	chromiumOxide("chromium oxide", "chrome green", 151.9904),
	citricAcid("citric acid", "sour salt", 192.12),
	copper("copper", "copper", 63.5463),
	copperSulfate("copper sulfate", "cupric sulfate", 159.609),
	cyanuricAcid("cyanuric acid", "isocyanuric acid", 129.07),
	dextrose("dextrose", "glucose", 180.16),
	dichloromethane("dichloromethane", "methylene chloride", 84.93),
	dimethylSulfoxide("dimethyl sulfoxide", "dmso", 78.13),
	ethanol("ethonol", "everclear", 46.07),
	ether("ether", "diethyl ether", 74.1216),
	ethyleneGlycol("ethylene glycol", "1 2 ethanediol", 62.07),
	eugenol("eugenol", "oil of clove", 164.2),
	formicAcid("formic acid", "methanoic acid", 46.03),
	fructose("fructose", "fruit sugar", 180.16),
	glucose("glucose", "dextrose", 180.16),
	glycerin("glycerin", "1 2 3 propentriol", 92.09),
	glycerol("glycerol", "glycerol", 92.09),
	gold("gold", "gold", 196.966569),
	gumArabic("gum arabic", "gum arabicia", 96.106),
	helium("helium", "helium", 4.0026022),
	hexamine("hexamine", "hexamethylenetetramine", 140.186),
	hydrogenGas("hydrogen gas", "hydrogen", 2.0162),
	hydrochloricAcid("hydrochloric acid", "masonry cleaner", 36.46094),
	hydrofluoricAcid("hydrofluoric acid", "glass etching solution", 20.01),
	hypochlorousAcid("hypochlorous acid", "laundry bleach", 52.46),
	hydroquinone("hydroquinone", "hydroquinone", 110.11),
	hydrogenPeroxide("hydrogen peroxide", "peroxide", 34.0147),
	iodine("iodine", "iodide", 253.80894),
	iron("iron", "iron", 55.8452),
	ferricChloride("ferric chloride", "etching solution", 162.2),
	ferricOxide("ferric oxide", "rust", 159.69),
	ferrousFerricOxide("ferrous ferric oxide", "magnetite", 231.533),
	ironSulfate("iron sulfate", "ferrous sulfate", 151.91),
	lacticAcid("lactic acid", "milk acid", 90.08),
	latex("latex", "liquid latex body paint", 90.0779),
	lead("lead", "lead", 207.2),
	lithium("lithium", "lithium", 6.941),
	Magnesium("magnesium", "fire starter", 24.3051),
	magnesiumCarbonate("magnesium carbonate", "athlete's chalk", 84.31),
	magnesiumHydroxide("magnesium hydroxide", "milk of magnesia", 58.3197),
	magnesiumSilicate("magnesium silicate", "talc", 379.266),
	magnesiumSulfate("magnesium sulfate", "epsom salt", 120.366),
	magnesiumChloride("magnesium chloride", "nigari", 95.211),
	magnesiumDioxide("magnesium dioxide", "pyrolusite", 86.9368),
	mercury("mercury", "quicksilver", 200.5923),
	methane("methane", "natural gas", 16.04),
	methanol("methanol", "methyl alcohol", 32.04),
	methylEthylKentone("butane", "methyl ethyl ketone", 72.11),
	mekp("methyl ethyl ketone peroxide", "mekp", 210.22),
	mibk("methyl isobutyl ketone", "mibk", 100.16),
	methyleneBlue("methylene blue", "methidote", 319.85),
	methyleneChloride("methylene chloride", "dichloromethane", 84.93),
	methylSalicylate("methyl salicylate", "oil of wintergreen", 152.15),
	monosodiumGlutamate("monosodium glutamate", "msg", 169.111),
	naphthalene("naphthalene", "moth balls", 128.17),
	nickel("nickel", "nickel", 58.693442),
	nitrogen("nitrogen", "liquid nitrogen", 142.6),
	nitrousOxide("nitrous oxide", "whipping gas", 44.013),
	oxalicAcid("oxalic acid", "rust remover", 90.03),
	oxygen("oxygen", "oxygen", 31.998),
	paradichloride("paradichloride", "1 4 dichlorobenzene", 147.00),
	phenol("phenol", "carbolic acid", 94.11),
	phenolphthalein("phenolphthalein", "phenolphthalein", 318.32),
	phenolRed("phenol red", "phenolsulfonephthalein", 354.38),
	phosphoricAcid("phosphoric acid", "ph down", 98),
	potassiumAlum("potassium aluminum sulfate", "potassium alum", 258.205),
	potassiumBitartrate("potassium bitartrate", "creame of tartar", 188.177),
	potassiumCarbonate("potassium carbonate", "potash", 138.205),
	potassiumBromide("potassium bromide", "potassium bromide", 119.002),
	potassiumChloride("potassium chloride", "salt substitute", 74.5513),
	potassiumDichromate("potassium dichromate", "potassium dichromate", 294.185),
	potassiumHydroxide("potassium hydroxide", "caustic potash", 56.11),
	potassiumIodide("potassium iodide", "radiation pills", 166.0028),
	potassiumMetabisulfite("potassium metabisulfite", "campden tablets", 222.32),
	potassiumNitrate("potassium nitrate", "saltpeter", 101.1032),
	potassiumPermanganate("potassium permanganate", "clearwater", 158.034),
	potassiumSodiumTartrate("potassium sodium tartrate", "rochelle salt", 282.1),
	propane("propane", "propane", 44.1),
	propanol("2 propanol", "isopropyl alcohol", 60.1),
	siliconCarbide("silocon carbide", "carborundum", 40.1),
	siliconDioxide("silicon dioxide", "sand", 60.08),
	silver("silver", "silver", 107.8682),
	sodiumAcetate("sodium acetate", "sodium acetate", 82.03),
	soliumBorate("sodium borate", "hand warmer", 201.22),
	sodiumBicarbonate("sodium bicarbonate", "baking soda", 84.007),
	disodiumPhosphate("disodium phosphate", "ph down", 141.96),
	sodiumBisulfate("sodium bisulfate", "ph down", 120.06),
	sodiumBromide("sodium bromide", "hot tub salt", 102.89),
	sodiumCarbonate("sodium carbonate", "washing soda", 105.99),
	sodiumChlorate("sodium chlorate", "sodium chlorate", 106.44),
	sodiumChloride("sodium chloride", "sodium chloride", 58.44),
	sodiumFluoride("sodium fluoride", "sodium fluoride", 41.988173),
	sodiumHexametaphosphate("sodium hexametaphosphate", "sodium polymetaphosphate", 611.7704),
	sodiumHydroxide("sodium hydroxide", "lye", 39.9971),
	sodiumHypochlorite("sodium hypochlorite", "bleach", 74.442),
	sodiumNitrate("sodium nitrate", "chile saltpeter", 84.9947),
	sodiumMetabisulfite("sodium metabisulfite", "campden tablets", 190.107),
	sodiumPercarbonate("sodium percarbonate", "sodium carbonate peroxyhydrate", 157.01),
	sodiumPhosphate("sodium phosphate", "tri sodium phosphate", 163.941),
	sodiumSulfite("sodium sulfite", "sodium sulfite", 126.043),
	sodiumSulfate("sodium sulfate", "sodium sulfate", 142.04),
	sodiumTetraborateDecahydrate("sodium tetraborate decahydrate", "borax", 201.22),
	sodiumThiosulfate("sodium thiosulfate", "hypo", 158.11),
	stearicAcid("stearic acid", "candle hardener", 284.48),
	sucrose("sucrose", "sugar", 342.3),
	sulfer("sulfer", "sulphur", 32.0661),
	sulfuricAcid("sulfuric acid", "vitriol", 98.079),
	tannicAcid("tannic acid", "tannin", 1701.2),
	tartaricAcid("tartaric acid", "wine preservative", 150.087),
	tetrachloroethylene("tetrachloroethylene", "tetrachloroethene", 165.83),
	thymolphthalein("thymolphthalein", "disappearing ink", 430.54),
	titaniumDioxide("titanium dioxide", "titanium white", 79.866),
	trichloroethane("trichloroethane", "1 1 1 trichloroethane", 133.4),
	tetrafluoroethane("tetrafluoroethane", "1 1 1 2 tetrafluoroethane", 102.03),
	thiourea("thiourea", "thiocarbamide", 76.12),
	toluene("toluene", "methylbenzene", 92.14),
	trichloroethylene("trichloroethylene", "trichloroethene", 131.39),
	tungsten("tungsten", "wolfram", 183.84),
	urea("urea", "ice melter", 60.06),
	xylene("xylene", "dimethylbenzene", 106.165),
	zinc("zinc", "zink", 65.382),
	zincChloride("zinc chloride", "tinner's fluid", 136.315),
	zincOxide("zinc oxide", "pompholyx", 81.408),
	zincSulfate("zinc sulfate", "zinc sulfate", 161.47);
	
	private final String compoundName;
	private final String commonName;
	private final double mass;
	
	CompoundName(String compoundName, String commonName, double mass) {
		this.compoundName = compoundName;
		this.commonName = commonName;
		this.mass = mass;
	}
	
	public String compoundName() {
		return this.compoundName;
	}
	
	public String commonName() {
		return this.commonName;
	}
	
	public double mass() {
		return this.mass;
	}

}